namespace:
  name: dev
  appname: myk8sapp

replicaCount: 1
   
service:
  port: 8889
  targetPort: 80
    #  type: LoadBalancer 
  type: NodePort  
    #  type: ClusterIP

image:
  repository: ritchie229/k8s_study:myk8sapp
  containerPort: 80

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
