namespace:
  name: prod
  appname: myk8sapp

replicaCount: 1
   
service:
  port: 8888
  targetPort: 80
    #type: ClusterIP 
    #type: NodePort 
  type: LoadBalancer 

image:
  repository: ritchie229/ritchie_docker:net_containers
  containerPort: 80

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
  iitargetMemoryUtilizationPercentage: 50
